theme: minima
title: Github introductions
author: Lorenzo Salazar 
Description: Customizing my site. 


# H1 header
###### This is my first header


![Image of Yaktocat](https://octodex.github.com/images/yaktocat.png)




``` javascript
var myVar = "Hello, world!";
```
- [ ] Turn on GitHub Pages
- [ ] Outline my portfolio
- [ ] Introduce myself to the world
- [ ] Finish the assignment. 
